import assert from "node:assert/strict";
import { describe, test } from "node:test";

process.env.DATABASE ??= "postgres://user:password@localhost:5432/test";

const { CLIENT_FINGERPRINT_PATTERN, createClientFingerprint, isClientFingerprint } = require("./Fingerprint") as typeof import("./Fingerprint");

describe("client fingerprint generation", () => {
    test("generates Discord-style snowflake fingerprints", () => {
        const fingerprint = createClientFingerprint();

        assert.match(fingerprint, CLIENT_FINGERPRINT_PATTERN);
        assert.equal(isClientFingerprint(fingerprint), true);
    });

    test("rejects malformed client fingerprints", () => {
        assert.equal(isClientFingerprint(undefined), false);
        assert.equal(isClientFingerprint("not-a-fingerprint"), false);
    });

    test("rejects shape-compatible fingerprints that were not generated by the server", () => {
        assert.equal(isClientFingerprint("1234567890.dGhpcy1pcy1ub3QtdGhlLWhhc2g="), false);
    });

    test("rejects tampered generated fingerprints", () => {
        const [snowflake, digest] = createClientFingerprint().split(".", 2);

        assert.equal(isClientFingerprint(`${snowflake}.${digest.slice(0, -1)}A`), false);
    });
});
